### PR TITLE
2. Security Context

### PR DESCRIPTION
**Pull request by emanjon**

### CODE REVIEW

**Comment by emanjon** [comment]
-The signature parameters are not signature parametes, they are part of the public key algorithm. The format of the public key algorithm depends on the types of credentials used, with CWT it is a COSE key type and Key Parameters, in X.509 it is a SubjectPublicKeyInfoAlgorithm. The public key algorith would typically be stored with the keys.

-The use of AEAD with signatures and without signatures are two completely different use cases with completely different security properties. It does not make sense to have a signle AEAD algorithm here as it increases source authentication with up to 16 bytes.

-Pairwise only deployments should not be forced to implement signatures.

-"Secret Derivation Algorithm MUST take value from the "Value" column of the "COSE Algorithms" Registry {{COSE.Algorithms}}" It makes no sense to mandate how the context in implemented in detail.

-When EdDSA are used for both signatues and pairwise, it should be forbidden to use them in other protocols.

- I don't understand this parameter obsession. It is extremely long and makes the whole specification and protocol feel extremly complicated. Frankly, I don't see much use at all.

**Comment by emanjon** [comment]
The name Secret Derivation Algorithm  is a bit strange. According to COSE this is a Key Agreement Algorithm. I suggest changing to "Pairwise Key Agreement Algorithm".
If the signature algorithms is protected in the external_aad, this algorithm should as well.
The key derivation in the Key Agreeent algorithm may not be HKDF. The key derivation included in the key agreement algorithm is used to derive the shared secret, it should not be used to derive the sender keys. The RFC 8613 HKDF Algorithm should be used in the derivation below.
Pairwise Sender Key = HKDF(Sender Key, Shared Secret, info, L)

**Comment by emanjon** [comment]
The draft does not dicuss key formats at all. Typical formats to use would be CWT, X509 and C509. The draft needs to discuss this at least shortly.
The public key credential includes the public key algorithm, something that the draft calls signature algorithms.
The public key credential should be included in the external_aad, COSE does not do this automatically for you.

**Comment by marco-tiloca-sics** [comment]
Manually addressed in branch "v-12", see commit https://github.com/core-wg/oscore-groupcomm/commit/b7b044555f43763e0e32d5fcd2312a4032843420

**Pull request closed without merging**
